# Generated by Django 3.0.5 on 2020-04-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0003_auto_20200424_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
