# Generated by Django 3.0.5 on 2020-04-24 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roomApp', '0002_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby_name', models.CharField(max_length=30)),
                ('lobby_description', models.TextField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_creator', to=settings.AUTH_USER_MODEL)),
                ('rooms', models.ManyToManyField(to='roomApp.Room')),
                ('users', models.ManyToManyField(related_name='lobby_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
