# Generated by Django 3.0.5 on 2020-04-25 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('task_title', models.CharField(max_length=40)),
                ('task_description', models.TextField()),
                ('date', models.DateTimeField()),
                ('is_done', models.BooleanField()),
                ('asignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignee', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=30)),
                ('room_description', models.TextField()),
                ('is_private', models.BooleanField()),
                ('room_password', models.IntegerField()),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_creator', to=settings.AUTH_USER_MODEL)),
                ('tasks', models.ManyToManyField(to='YoTask.Task')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby_name', models.CharField(max_length=30)),
                ('lobby_password', models.IntegerField()),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_creator', to=settings.AUTH_USER_MODEL)),
                ('rooms', models.ManyToManyField(to='YoTask.Room')),
                ('users', models.ManyToManyField(related_name='lobby_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
