# Generated by Django 3.0.5 on 2020-04-25 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YoTask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='lobby_password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_password',
            field=models.TextField(),
        ),
    ]
